### ISSUE TITLE
코드 리뷰 : 우준호

### ISSUE THREAD

**Issue by noggong** [verdantjuly/kiosk#17]
https://github.com/verdantjuly/kiosk/blob/9c7015a1b8ea4b7c03bc345867f02f2775eac844/src/controllers/itmes.controller.js#L15C42-L15C42

- status, message 를 이런식으로  service 에서 만들어주는것은 좋지 않습니다. 함수는 자신의 역할만 하고, 처리 결과만을 응답하는것이 좋습니다.

https://github.com/verdantjuly/kiosk/blob/9c7015a1b8ea4b7c03bc345867f02f2775eac844/src/routes/receipts.route.js#L9C1-L9C1
- url 에서 receipts 가 자원이라면 receipts id 가 내려가야 합니다. restAPI 형식으로 확인 변경 해 보세요.

https://github.com/verdantjuly/kiosk/blob/9c7015a1b8ea4b7c03bc345867f02f2775eac844/src/services/items.service.js#L13
- 이런 message class 가 누구를 위하고 어떤것을 위해서 사용되는지 고민해 보세요. 

https://github.com/verdantjuly/kiosk/blob/9c7015a1b8ea4b7c03bc345867f02f2775eac844/src/services/items.service.js#L13
- 상품 추가는 권한이 없어도 가능한 것인가요?

https://github.com/verdantjuly/kiosk/blob/9c7015a1b8ea4b7c03bc345867f02f2775eac844/src/repositories/items.repository.js#L5
- repository 는 하나의 entity (model) 만 연결해서 사용하는것이 좋습니다.

https://github.com/verdantjuly/kiosk/blob/9c7015a1b8ea4b7c03bc345867f02f2775eac844/src/repositories/items.repository.js#L40
- 함수이름이  checkamount 인데 하는 역할은 id 로 아이템을 가져옵니다. 올바른 네이밍을 고민해 보세요.

## 종합
- 전반적으로 잘 구현했고, 고민도 많이 하신것으로 보입니다.
- 다만 생각이 너무 깊이 가서, 불필요한 코드로 인해 (new Message 등) 오히려 코드의 복잡도가 올라가고 코드를 이해하기 어렵게 만든듯 합니다. 왜 코드를 추가하고 어떤 용도인지를 분명히 해보시면 좋을듯 합니다.
- 함수의 역할을 잘 정하고 그에 맞는 이름, 파라미터, 결과값을 설정해보시면 좋겠습니다.

**Comment by verdantjuly** [comment]
- status와 메시지를 controller layer에서 만들어서 함수의 단일 역할을 지키겠습니다.
- 앞으로는 new Message 대신에 에러 객체를 활용하도록 할 예정입니다.
- REST API 형식에 맞는 url을 만들어보겠습니다.
- 권한 설정 부분에 유의하겠습니다.
- repository는 하나의 엔티티(모델)만을 연결해 사용할 수 있도록 설계해 보겠습니다.
- 함수의 역할에 대해 맞는 이름, 파라미터, 결과값을 모두 고려해서 설정하도록 하겠습니다. 

우준호 튜터 님 항상 감사드립니다! 
조언해 주신 부분들을 유념해서 다음에는 더 좋은 코드를 만들어보겠습니다!
